services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BitLab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: REDACTED!
      SPRING_DATA_REDIS_HOST: redis

  # основная база данных для работы приложения
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: BitLab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REDACTED!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    # база данных для тестирования
  postgres-test:
      image: postgres:16
      container_name: 'test-database-container'
      environment:
        POSTGRES_DB: BitLab
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: REDACTED!
      ports:
        - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"