spring.application.name=personal-finance
server.port=8080
spring.thymeleaf.cache=false

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/BitLab}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

finnhub.api.key=${FINNHUB_API_KEY}
finnhub.news.limit=20