spring.application.name=personal-finance
server.port=8080
spring.thymeleaf.cache=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:postgresql://localhost:5432/BitLab
spring.datasource.username=postgres
spring.datasource.password=REDACTED!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

finnhub.api.key=d8pdv1pr01qgoi5ik4egd8pdv1pr01qgoi5ik4f0