spring.application.name=personal-finance
server.port=8080
spring.thymeleaf.cache=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.datasource.url=jdbc:postgresql://localhost:5432/BitLab
spring.datasource.username=postgres
spring.datasource.password=REDACTED!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

finnhub.api.key=d8pdv1pr01qgoi5ik4egd8pdv1pr01qgoi5ik4f0
finnhub.news.limit=20